// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoonBuck.DataAccess.Data;

#nullable disable

namespace MoonBuck.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231021084141_seedroleandslot")]
    partial class seedroleandslot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoonBuck.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Chef"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Cashier"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Waiter"
                        });
                });

            modelBuilder.Entity("MoonBuck.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CafeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFilled")
                        .HasColumnType("bit");

                    b.Property<double>("PayRate")
                        .HasColumnType("float");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Slots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CafeName = "MoonBuck Toa Payoh",
                            EndTime = new DateTime(2023, 10, 23, 2, 17, 41, 326, DateTimeKind.Local).AddTicks(4691),
                            IsFilled = false,
                            PayRate = 9.0,
                            RoleId = 1,
                            StartTime = new DateTime(2023, 10, 22, 16, 41, 41, 326, DateTimeKind.Local).AddTicks(4677)
                        },
                        new
                        {
                            Id = 2,
                            CafeName = "MoonBuck Toa Payoh",
                            EndTime = new DateTime(2023, 10, 24, 2, 17, 41, 326, DateTimeKind.Local).AddTicks(4693),
                            IsFilled = false,
                            PayRate = 9.0,
                            RoleId = 2,
                            StartTime = new DateTime(2023, 10, 23, 16, 41, 41, 326, DateTimeKind.Local).AddTicks(4693)
                        },
                        new
                        {
                            Id = 3,
                            CafeName = "MoonBuck Tampines",
                            EndTime = new DateTime(2023, 10, 24, 2, 17, 41, 326, DateTimeKind.Local).AddTicks(4695),
                            IsFilled = false,
                            PayRate = 9.0,
                            RoleId = 2,
                            StartTime = new DateTime(2023, 10, 23, 16, 41, 41, 326, DateTimeKind.Local).AddTicks(4695)
                        },
                        new
                        {
                            Id = 4,
                            CafeName = "MoonBuck Hougang",
                            EndTime = new DateTime(2023, 10, 25, 2, 17, 41, 326, DateTimeKind.Local).AddTicks(4697),
                            IsFilled = false,
                            PayRate = 9.0,
                            RoleId = 2,
                            StartTime = new DateTime(2023, 10, 24, 16, 41, 41, 326, DateTimeKind.Local).AddTicks(4697)
                        });
                });

            modelBuilder.Entity("MoonBuck.Models.Slot", b =>
                {
                    b.HasOne("MoonBuck.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
